name: eha_gis_assessment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - shapely
  - fiona
  - psycopg
  - pg8000
  - matplotlib
  - jupyterlab
  - libpysal=4.14.1
  - esda=2.9.0
